[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wikirarp"
version = "0.2.0"
description = "A fast, lightweight ARP network scanner and Python library."
readme = "README.md"
authors = [{ name = "wikirity" }]
requires-python = ">=3.8"
dependencies = [
    "scapy",
    "colorama",
    "mac_vendor_lookup"
]

[project.scripts]
wikirarp = "wikirarp.cli:main"
